name: translog
interval: 1
count: 5
randomizeEvents: true
earliest: -3s
latest: now
tokens:
  - name: ts-ymdhmsms-regex  # References existing default token
  - name: transtype          # An inline token defined in this YAML
    format: regex
    token: transType=(\w+)
    type: weightedChoice
    weightedChoice:
    - weight: 3
      choice: New
    - weight: 5
      choice: Change
    - weight: 1
      choice: Delete
  - name: integerid
    format: template
    type: script
    script: >
      if state["id"] == nil then
        state["id"] = 0
      else
        state["id"] = state["id"] + 1
      end
      return state["id"]
  - name: guid-template
    format: template
    token: $guid$
    type: random
    replacement: guid
  - name: usernames-template
    format: template
    token: $username$
    type: choice
    sample: usernames.sample
  - name: markets-city 
    format: template
    token: $city$
    type: fieldChoice
    sample: markets.csv
    srcField: city
    group: 1
  - name: markets-state 
    format: template
    token: $state$
    type: fieldChoice
    sample: markets.csv
    srcField: state
    group: 1
  - name: markets-zip
    format: template
    token: $zip$
    type: fieldChoice
    sample: markets.csv
    srcField: zip
    group: 1
  - name: value
    format: regex
    token: value=(\d+)
    type: random
    replacement: float
    precision: 3
    lower: 0
    upper: 10

lines:
  - _raw: 2012-09-14 16:30:20,072 line1 transType=ReplaceMe transID=$integerid$ transGUID=$guid$ userName=$username$ city="$city$" state=$state$ zip=$zip$ value=0
  - _raw: 2012-09-14 16:30:20,072 line2 transType=ReplaceMe transID=$integerid$ transGUID=$guid$ userName=$username$ city="$city$" state=$state$ zip=$zip$ value=0