global:
  samplesDir:
  - $SPLUNK_HOME/etc/apps/SA-Gogen/lookups
generators:
  - name: cpu
    fileName: $SPLUNK_HOME/etc/apps/SA-Gogen/bin/lib/cpu.lua
    options:
      minCPU: 80.0
      maxCPU: 95.0
      numCPUs: 2
samples:
  - name: cpu
    description: Generate CPU Metrics
    notes: >
      Generates CPU usage in the form of Splunk's UNIX TA
    generator: cpu
    interval: 1
    latest: now
    begin: -1s
    end: now
    tokens:
    - name: host
      type: fieldChoice
      srcField: host
      sample: allhosts.csv
      disabled: true
    lines:
    - index: os
      sourcetype: cpu
      source: cpu
      host: $host$
      _raw: |- 
        
    - index: os
      sourcetype: cpu
      source: cpu
      host: $host$
      _raw: CPU=$CPU$ pctUser=$pctUser$ pctSystem=$pctSystem$ pctIowait=$pctIowait$ pctIdle=$pctIdle$