global:
  samplesDir:
    - $SPLUNK_HOME/etc/apps/SA-Gogen/lookups
generators:
  - name: iostat
    fileName: $SPLUNK_HOME/etc/apps/SA-Gogen/libs/iostat.lua
    options:
      highWrites: 0
      highReads: 0
      maxOps: 1000
      avgKB: 0.512
      maxTime: 100
samples:
  - name: iostat
    description: Generate Iostat Usage Metrics
    notes: >
      Generates iostat usage from the Splunk UNIX TA
    generator: iostat
    interval: 1
    count: 1
    earliest: now
    latest: now
    begin: -1s
    end: now
    tokens:
    - name: host
      type: fieldChoice
      srcField: host
      sample: allhosts.csv
      disabled: true
    - name: disks
      type: fieldChoice
      srcField: disk
      sample: disks.csv
      disabled: false
    lines:
    - index: os
      sourcetype: iostat
      source: iostat
      host: $host$
      _raw: 
    - index: os
      sourcetype: iostat
      source: iostat
      host: $host$
      _raw: Device=$device$ rReq_PS=$rrps$ wReq_PS=$wrps$ rKB_PS=$rkbps$ wKB_PS=$wkbps$ avgWaitMillis=$avgwait$ avgSvcMillis=$avgsvc$ bandwUtilPct=$bwutil$