---
debug: false
verbose: false
generatorWorkers: 1
outputWorkers: 1
rotInterval: 1
output:
    outputter: stdout                # Default outputter for events
    outputTemplate: raw              # Default output template for events   