global:
    samplesDir:
    - $GOGEN_HOME/examples/nixOS
    - examples/nixOS
  samples:
  - name: cpu
    description: Generate CPU Metrics
    notes: |
      Generates CPU usage in the form of Splunk's UNIX TA
    disabled: false
    generator: cpu
    rater: default
    interval: 1
    earliest: now
    latest: now
    tokens:
    - name: host
      format: ""
      token: ""
      type: fieldChoice
      sample: allhosts.csv
      field: _raw
      srcField: host
      fieldChoice:
      - group: api
        host: appserver-01
        ip: 10.2.1.133
        mac: BE:21:D7:EF:CD:E2
        nics: "2"
      - group: api
        host: appserver-02
        ip: 10.2.1.134
        mac: 2A:24:90:9B:AF:2C
        nics: "2"
      omitempty: false
    lines:
    - _raw: "CPU\tpctUser\tpctNice\tpctSystem\tpctIowait\tpctIdle\nall\t$pctUserAll$\t0\t$pctSystemAll$\t$pctIowaitAll$\t$pctIdleAll$"
      host: $host$
      index: os
      source: cpu
      sourcetype: cpu
    - _raw: "$CPU$\t$pctUser$\t0\t$pctSystem$\t$pctIowait$\t$pctIdle$"
      host: $host$
      index: os
      source: cpu
      sourcetype: cpu
    field: _raw
  mix: []
  generators:
  - name: cpu
    options:
      maxCPU: 75
      minCPU: 30
      numCPUs: 8
    script: |-
      hosts = getFieldChoice("host", "host")
      for i, host in ipairs(hosts) do
          events = { }
          setToken("host", host, "host")
  
          totalCPU = math.random() + math.random(options["minCPU"], options["maxCPU"])
          pctUserAll = round(math.random() * totalCPU, 2)
          pctSystemAll = round(totalCPU - pctUserAll, 2)
          pctIowaitAll = round(math.random() * 0.1, 2)
          pctIdleAll = round(100 - pctUserAll - pctSystemAll, 2)
  
          setToken("pctUserAll", pctUserAll)
          setToken("pctSystemAll", pctSystemAll)
          setToken("pctIowaitAll", pctIowaitAll)
          setToken("pctIdleAll", pctIdleAll)
          l = getLine(0)
          l = replaceTokens(l)
          table.insert(events, l)
  
          for i=1,tonumber(options["numCPUs"]),1
          do
              oneCPU = round(math.random() * totalCPU, 2)
              pctUser = round(math.random() * oneCPU, 2)
              pctSystem = round(oneCPU - pctUser, 2)
              pctIowait = round(math.random() * 0.1, 2)
              pctIdle = round(100 - pctUser - pctSystem, 2)
              setToken("CPU", oneCPU)
              setToken("pctUser", pctUser)
              setToken("pctSystem", pctSystem)
              setToken("pctIowait", pctIowait)
              setToken("pctIdle", pctIdle)
              l = getLine(1)
              l = replaceTokens(l)
              table.insert(events, l)
          end
          send(events)
      end
    fileName: $GOGEN_HOME/examples/nixOS/cpu.lua