global:
    samplesDir:
    - $GOGEN_HOME/examples/nixOS
    - examples/nixOS
  samples:
  - name: df
    description: Generate Disk Usage Metrics
    notes: |
      Generates Disk Usage in the form of a df command from the Splunk UNIX TA
    disabled: false
    generator: df
    rater: default
    interval: 60
    earliest: now
    latest: now
    tokens:
    - name: disks
      format: ""
      token: ""
      type: fieldChoice
      sample: disks.csv
      field: _raw
      srcField: disk
      fieldChoice:
      - disk: /dev/sda1
        mount: /
      - disk: /dev/sdb1
        mount: var
      - disk: /dev/sda2
        mount: home
      - disk: /dev/sdb2
        mount: etc
      omitempty: false
    - name: host
      format: ""
      token: ""
      type: fieldChoice
      sample: allhosts.csv
      field: _raw
      srcField: host
      fieldChoice:
      - group: api
        host: appserver-01
        ip: 10.2.1.133
        mac: BE:21:D7:EF:CD:E2
        nics: "2"
      - group: api
        host: appserver-02
        ip: 10.2.1.134
        mac: 2A:24:90:9B:AF:2C
        nics: "2"
      omitempty: false
    lines:
    - _raw: "Filesystem\tType\tSize\tUsed\tAvail\tUsePct\tMountedOn"
      host: $host$
      index: os
      source: df
      sourcetype: df
    - _raw: "$fs$\text4\t$totalGB$G\t$usedGB$G\t$availGB$G\t$usedPct$%\t$mnt$"
      host: $host$
      index: os
      source: df
      sourcetype: df
    field: _raw
  mix: []
  generators:
  - name: df
    options:
      maxDiskUsedPct: 69
      minDiskUsedPct: 50
      numDisks: 4
      totalGBperDisk: 931
    script: |
      hosts = getFieldChoice("host", "host")
      mounts = getFieldChoice("disks", "mount")
      disks = getFieldChoice("disks", "disk")
      for i, host in ipairs(hosts) do
          setToken("host", host, "host")
          events = { }
          l = getLine(0)
          l = replaceTokens(l)
          table.insert(events, l)
  
          for i=1,#disks do
              usedPct = round(math.random() + math.random(options["minDiskUsedPct"], options["maxDiskUsedPct"]),2)
              usedGB = round((usedPct/100) * options["totalGBperDisk"])
              availGB = round(options["totalGBperDisk"] - usedGB)
              setToken("usedPct", usedPct)
              setToken("usedGB", usedGB)
              setToken("availGB", availGB)
              setToken("totalGB", options["totalGBperDisk"])
              if availGB < 1 then
                  setToken("fs", "/dev/sdb1")
                  setToken("mnt", "var")
              else
                  setToken("fs", disks[i])
                  setToken("mnt", mounts[i])
              end
              l = getLine(1)
              l = replaceTokens(l)
              table.insert(events, l)
          end
          send(events)
      end
    fileName: $GOGEN_HOME/examples/nixOS/df.lua