global:
    samplesDir:
    - $GOGEN_HOME/examples/nixOS
    - examples/nixOS
  samples:
  - name: vmstat
    description: Generate Memory Usage Metrics
    notes: |
      Generates memory Usage in the form of a vmstat command from the Splunk UNIX TA
    disabled: false
    generator: vmstat
    rater: default
    interval: 60
    earliest: now
    latest: now
    tokens:
    - name: host
      format: ""
      token: ""
      type: fieldChoice
      sample: allhosts.csv
      field: _raw
      srcField: host
      fieldChoice:
      - group: api
        host: appserver-01
        ip: 10.2.1.133
        mac: BE:21:D7:EF:CD:E2
        nics: "2"
      - group: api
        host: appserver-02
        ip: 10.2.1.134
        mac: 2A:24:90:9B:AF:2C
        nics: "2"
      omitempty: false
    lines:
    - _raw: "memTotalMB\tmemFreeMB\tmemUsedMB\tmemFreePct\tmemUsedPct\tpgPageOut\tswapUsedPct\tpgSwapOut\tcSwitches\tinterrupts\tforks\tprocesses\tthreads\tloadAvg1mi\twaitThreads\tinterrupts_PS\tpgPageIn_PS\tpgPageOut_PS"
      host: $host$
      index: os
      source: df
      sourcetype: df
    - _raw: "$memTotalMB$\t$memFreeMB$\t$memUsedMB$\t$memFreePct$\t$memUsedPct$\t$pgPageOut$\t$swapUsedPct$\t$pgSwapOut$\t$cSwitches$\t$interrupts$\t$forks$\t$processes$\t$threads$\t$loadAvg1mi$\t$waitThreads$\t$interruptsPS$\t$pgPageInPS$\t$pgPageOutPS$"
      host: $host$
      index: os
      source: df
      sourcetype: df
    field: _raw
  mix: []
  generators:
  - name: vmstat
    options:
      maxMemUsedPct: 60
      minMemUsedPct: 5
      totalMB: 16000
    script: |-
      hosts = getFieldChoice("host", "host")
      for i, host in ipairs(hosts) do
          setToken("host", host, "host")
          events = { }
          l = getLine(0)
          l = replaceTokens(l)
          table.insert(events, l)
  
          memTotalMB = options["totalMB"]
          memUsedPct = round(math.random() + math.random(options["minMemUsedPct"], options["maxMemUsedPct"]),1)
          memFreePct = round(100-memUsedPct, 1)
          memFreeMB = memTotalMB * memFreePct / 100
          memUsedMB = memTotalMB - memFreeMB
          pgPageOut = math.random(1000000, 10000000)
          swapUsedPct = round(math.random(0, 200) / 100, 1)
          pgSwapOut = math.random(10000, 100000)
          cSwitches = math.random(1000000,5000000)
          interrupts = math.random(1000000,4000000)
          forks = math.random(10000,100000)
          processes = math.random(100,500)
          threads = math.random(1000,3000)
          loadAvg1mi = math.random(100,500) / 100
          waitThreads = 0
          interruptsPS = math.random(100000, 1000000) / 100
          pgPageInPS = math.random(1000, 15000) / 100
          pgPageOutPS = math.random(100000, 2000000) / 100
  
          tokens = { "memTotalMB", "memUsedPct", "memFreePct", "memFreeMB", "memUsedMB", "pgPageOut", "swapUsedPct", "pgSwapOut", "cSwitches", "interrupts", "forks", "processes", "threads", "loadAvg1mi", "waitThreads", "interruptsPS", "pgPageInPS", "pgPageOutPS"}
          for i, t in ipairs(tokens) do
              setToken(t, _G[t])
          end
          l = getLine(1)
          l = replaceTokens(l)
          table.insert(events, l)
          send(events)
      end
    fileName: $GOGEN_HOME/examples/nixOS/vmstat.lua