global:
  rotInterval: 1
  samplesDir:
  - $GOGEN_HOME/examples/common
  - examples/weblog
samples:
- name: weblog
  description: Weblog data in Apache common format
  notes: |
    Easily customizable for your own needs.  If you want your IP ranges, edit external_ips.sample.   To modify server hostnames and client IPs, modify webhosts.csv.  Useragents.sample is also pretty dated, so feel free to replace with a more modern list of user agents.
  disabled: false
  generator: sample
  rater: default
  interval: 1
  count: 142
  earliest: now
  latest: now
  begin: -1s
  end: now
  endIntervals: 1
  tokens:
  - name: ts-dmyhmsms-template
    format: template
    token: $ts$
    type: gotimestamp
    replacement: "02/Jan/2006:15:04:05"
################### clientip
  - name: clientip
    format: template
    token: $clientip$
    type: choice
    sample: external_ips.sample
    field: _raw
    # ip adress list
    choice:
    - 127.0.42.42
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 12.130.60.4
    - 12.130.60.5
    - 125.17.14.100
    - 128.241.220.82
    - 130.253.37.97
    - 131.178.233.243
    - 141.146.8.66
    - 142.162.221.28
    - 142.233.200.21
    - 194.215.205.19
    - 201.122.42.235
    - 201.28.109.162
    - 201.3.120.132
    - 201.42.223.29
    - 203.92.58.136
    - 212.235.92.150
    - 212.27.63.151
    - 217.132.169.69
    - 59.162.167.100
    - 74.125.19.106
    - 81.11.191.113
    - 82.245.228.36
    - 84.34.159.23
    - 86.212.199.60
    - 86.9.190.90
    - 87.194.216.51
    - 89.167.143.32
    - 90.205.111.169
    - 92.1.170.135
    - 1.16.0.0
    - 1.19.11.11
    - 27.1.0.0
    - 27.1.11.11
    - 27.35.0.0
    - 27.35.11.11
    - 27.96.128.0
    - 27.96.191.11
    - 27.101.0.0
    - 27.101.11.11
    - 27.102.0.0
    - 27.102.11.11
    - 27.160.0.0
    - 27.175.11.11
    - 27.176.0.0
    - 193.33.170.23
    - 194.146.236.22
    - 194.8.74.23
    - 195.216.243.24
    - 195.69.160.22
    - 195.69.252.22
    - 195.80.144.22
    - 200.6.134.23
    - 202.164.25.24
    - 203.223.0.20
    - 217.197.192.20
    - 62.216.64.19
    - 64.66.0.20
    - 69.80.0.18
    - 87.240.128.18
    - 89.11.192.18
    - 91.199.80.24
    - 91.205.40.22
    - 91.208.184.24
    - 91.214.92.22
    - 94.229.0.20
    - 94.229.0.21

################### user
  - name: user
    format: template
    token: $user$
    type: choice
    sample: user.sample
    field: _raw
    choice:
      - "-"


################### method
  - name: method
    format: template
    token: $method$
    type: choice
    sample: method.sample
    field: _raw
    # method list
    choice:
      - GET


################### URL
  - name: url
    format: template
    token: $url$
    type: choice
    sample: url.sample
    field: _raw
    choice:
    - http://shop.buttercupgames.com/cart.do?action=view&itemId=HolyGouda


################### version
  - name: version
    format: template
    token: $version$
    type: choice
    sample: version.sample
    field: _raw
    # version list
    choice:
      - HTTP/1.1


################### status
  - name: status
    format: template
    token: $status$
    type: weightedChoice
    field: _raw
    weightedChoice:
    - weight: 10
      choice: "200"
    - weight: 4
      choice: "301"
    - weight: 3
      choice: "404"
    - weight: 2
      choice: "503"


################### size
  - name: size
    format: template
    token: $size$
    type: choice
    sample: size.sample
    field: _raw
    # size list for byte 
    choice:
      - 1024


################### referer
  - name: referer
    format: template
    token: $referer$
    type: choice
    sample: referer.sample
    field: _raw
    # referer list
    choice:
      - "-"


################### useragent
  - name: useragent
    format: template
    token: $useragent$
    type: choice
    sample: useragents.sample
    field: _raw
    choice:
    - Mozilla/5.0 (Linux; U; Android 2.3.7; fr-fr; Nexus S Build/GRK39F) AppleWebKit/533.1
      (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
    - Mozilla/5.0 (iPad; U; CPU OS 4_3_1 like Mac OS X; en-us) AppleWebKit/533.17.9
      (KHTML, like Gecko) Version/5.0.2 Mobile/8G4 Safari/6533.18.5
    - Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_0_1 like Mac OS X; en_US) AppleWebKit
      (KHTML, like Gecko) Mobile [FBAN/FBForIPhone;FBAV/4.0.3;FBBV/4030.0;FBDV/iPhone3,1;FBMD/iPhone;FBSN/iPhone
      OS;FBSV/5.0.1;FBSS/2; FBCR/Pelephone;FBID/phone;FBLC/en_US;FBSF/2.0]
    - Mozilla/5.0 (Linux; U; Android 2.3.3; nb-no; HTC_DesireHD_A9191 Build/GRI40)
      AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
    - Mozilla/5.0 (Linux; U; Android 2.3.5; zh-cn; MI-ONE Plus Build/GINGERBREAD)
      AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
    - Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; DROID BIONIC Build/5.5.1_84_DBN-62_MR-11)
      AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
    - Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_0_1 like Mac OS X; en_US) AppleWebKit
      (KHTML, like Gecko) Mobile [FBAN/FBForIPhone;FBAV/4.0.3;FBBV/4030.0;FBDV/iPhone3,1;FBMD/iPhone;FBSN/iPhone
      OS;FBSV/5.0.1;FBSS/2; FBCR/vodafoneUK;FBID/phone;FBLC/en_US;FBSF/2.0]
    - Mozilla/5.0 (iPad; CPU OS 5_0_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like
      Gecko) 1Password/3.6.1/361009 (like Mobile/8C148 Safari/6533.18.5)
    - Mozilla/5.0 (iPhone; CPU iPhone OS 5_0_1 like Mac OS X) AppleWebKit/534.46 (KHTML,
      like Gecko) Version/5.1 Mobile/9A405 Safari/7534.48.3
    - Mozilla/5.0 (Linux; U; Android 2.2.1; en-us; ADR6400L Build/FRG83D) AppleWebKit/533.1
      (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
    - Mozilla/5.0 (iPad; CPU OS 5_0_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like
      Gecko) Version/5.1 Mobile/9A405 Safari/7534.48.3
    - Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; ADR6350 Build/GRJ22) AppleWebKit/533.1
      (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
    - Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_0_1 like Mac OS X; en_US) AppleWebKit
      (KHTML, like Gecko) Mobile [FBAN/FBForIPhone;FBAV/4.0.2;FBBV/4020.0;FBDV/iPhone3,1;FBMD/iPhone;FBSN/iPhone
      OS;FBSV/5.0.1;FBSS/2; FBCR/AT&T;FBID/phone;FBLC/en_US;FBSF/2.0]
    - Mozilla/5.0 (Linux; U; Android 2.2.3; en-us; Droid Build/FRK76) AppleWebKit/533.1
      (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
    - Mozilla/5.0 (iPad; CPU OS 5_0_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like
      Gecko) Mobile/9A405
    - Mozilla/5.0 (iPad; U; CPU OS 4_3_5 like Mac OS X; en-us) AppleWebKit/533.17.9
      (KHTML, like Gecko) Version/5.0.2 Mobile/8L1 Safari/6533.18.5
    - Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18
      (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16
    - BlackBerry9300/5.0.0.955 Profile/MIDP-2.1 Configuration/CLDC-1.1 VendorID/102
    - Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 like Mac OS X; en-us) AppleWebKit/533.17.9
      (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5
    - Mozilla/5.0 (Linux; U; Android 3.1; de-de; GT-P7510 Build/HMJ37) AppleWebKit/534.13
      (KHTML, like Gecko) Version/4.0 Safari/534.13

  lines:
  - _raw: $clientip$ - $user$ [$ts$] "$method$ $url$ 
      $version$" $status$ $size$ "$referer$" "$useragent$"
    host: $host$
    index: main
    source: /var/log/httpd/access_log
    sourcetype: access_combined
  field: _raw
  singlepass: true
mix: []
