global:
  samplesDir:
  - $SPLUNK_HOME/etc/apps/splunk_app_gogen/gogen_assets/samples
generators:
  - name: retailtransaction
    fileName: $SPLUNK_HOME/etc/apps/splunk_app_gogen/gogen_assets/generators/retail_transaction.lua
    singleThreaded: false
    options:
      users:
        - john
        - tom
        - sue
        - amy
        - fred
        - annie
        - george
        - emily
        - rick
        - alan
      traversaldelay:
        0: 10
        1: 30
        2: 30
        3: 30
        4: 30
        5: 30
        6: 30
        7: 60
    init:
        stage: 0
        cartitemcount: 0
        traversalsteps: 0
        maxtraversalsteps: 100
        cartrepeats: 0
        maxcartrepeats: 5
        sessionid: 0
samples:
  - name: transaction
    description: Generate a retail transaction
    notes: >
      Simulates a retail transaction with statefullness.Simulating multiple users is accomplished by running multiple
      generator threads which each maintain their own state.You can set this thread size value in the Modular Input setup.
    generator: retailtransaction
    interval: 1
    endIntervals: 10
    tokens:
        - name: ts-dmyhmsms-regex
          format: regex
          token: "(\\d{1,2}/\\w{3}/\\d{4}\\s\\d{2}:\\d{2}:\\d{2}:\\d{1,3})"
          type: timestamp
          replacement: "%d/%b/%Y %H:%M:%S:%L"
        - name: host
          format: template
          type: fieldChoice
          srcField: host
          field: host
          sample: webhosts.csv
        - name: clientip
          format: template
          type: choice
          sample: external_ips.sample
        - name: useragent
          format: template
          type: choice
          sample: useragents.sample
        - name: saleamount
          format: template
          type: random
          replacement: float
          precision: 2
          lower: 1.0
          upper: 4000.0
        - name: itemcode
          type: choice
          sample: itemcode.sample
          disabled: true
        - name: paymenttype
          format: template
          type: choice
          sample: paymenttype.sample
        - name: paymentstatus
          format: template
          type: weightedChoice
          weightedChoice:
          - weight: 20
            choice: SUCCESS
          - weight: 3
            choice: FAILURE
    lines:
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=login sessionid=$session$ clientip=$clientip$ useragent=$useragent$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=landingpage sessionid=$session$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=searchitem sessionid=$session$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=viewitem sessionid=$session$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=additem sessionid=$session$ itemcode=$itemcode$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=checkout sessionid=$session$ itemcount=$itemcount$ saleamount=$saleamount$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=payment paymentstatus=$paymentstatus$ sessionid=$session$ paymenttype=$paymenttype$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=logout sessionid=$session$
    - index: main
      sourcetype: retail_transaction
      source: gogen
      host: $host$
      _raw: 29/Apr/2013 18:09:05:132 user=$user$ action=removeitem sessionid=$session$ itemcode=$itemcode$
