samples:
  - name: trig_metrics
    interval: 1
    count: 1
    tokens:
      - name: sin
        format: template
        type: script
        script: >
            math.randomseed(os.time())
            local x = math.random(1,100)
            return math.abs(math.sin(x))
      - name: cos
        format: template
        type: script
        script: >
            math.randomseed(os.time())
            local x = math.random(1,100)
            return math.abs(math.cos(x))
      - name: tan
        format: template
        type: script
        script: >
            math.randomseed(os.time())
            local x = math.random(1,100)
            return math.abs(math.tan(x))
    lines:
    - _raw: sin=$sin$ cos=$cos$ tan=$tan$
      index: main
      sourcetype: trig_metrics
      source: gogen